# Generated by Django 5.1.7 on 2025-04-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='addmoney_cateory',
            new_name='addmoney_category',
        ),
    ]
