# Generated by Django 5.1.7 on 2025-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0002_rename_addmoney_cateory_expenses_addmoney_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
